"""NetSentry — Data models for network state."""
from __future__ import annotations

import json
import time
from dataclasses import asdict, dataclass, field
from typing import Any, Dict, List, Optional

from shared import AlertLevel


# ── Socket entry ───────────────────────────────────────────────
@dataclass
class SocketEntry:
    """A single network socket from /proc/net/."""
    proto: str              # "tcp" | "udp"
    local_ip: str           # "0.0.0.0"
    local_port: int         # 22
    remote_ip: str          # "0.0.0.0" or peer
    remote_port: int        # 0 or peer port
    state: str              # "LISTEN" | "ESTABLISHED" | ...
    state_code: str         # "0A" raw hex
    uid: int
    inode: int
    pid: Optional[int] = None
    process_name: Optional[str] = None
    cmdline: Optional[str] = None
    remote_hostname: Optional[str] = None

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> SocketEntry:
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})


# ── Alert ──────────────────────────────────────────────────────
@dataclass
class Alert:
    """Security alert generated by the alert engine."""
    level: AlertLevel
    port: int
    proto: str
    process_name: Optional[str]
    pid: Optional[int]
    message: str
    timestamp: float = field(default_factory=time.time)

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> Alert:
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})


# ── Snapshot (full state at a point in time) ───────────────────
@dataclass
class Snapshot:
    """Complete network state snapshot written to JSON."""
    timestamp: float = field(default_factory=time.time)
    poll_interval_ms: int = 2000
    listening: List[SocketEntry] = field(default_factory=list)
    established: List[SocketEntry] = field(default_factory=list)
    alerts: List[Alert] = field(default_factory=list)
    summary: Dict[str, int] = field(default_factory=lambda: {
        "total_listening": 0,
        "total_established": 0,
        "alert_count": 0,
    })

    # ── Serialisation ──────────────────────────────────────────
    def to_dict(self) -> dict[str, Any]:
        return {
            "timestamp": self.timestamp,
            "poll_interval_ms": self.poll_interval_ms,
            "listening": [asdict(e) for e in self.listening],
            "established": [asdict(e) for e in self.established],
            "alerts": [asdict(a) for a in self.alerts],
            "summary": self.summary,
        }

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), ensure_ascii=False)

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> Snapshot:
        return cls(
            timestamp=d.get("timestamp", time.time()),
            poll_interval_ms=d.get("poll_interval_ms", 2000),
            listening=[SocketEntry.from_dict(e) for e in d.get("listening", [])],
            established=[SocketEntry.from_dict(e) for e in d.get("established", [])],
            alerts=[Alert.from_dict(a) for a in d.get("alerts", [])],
            summary=d.get("summary", {}),
        )

    @classmethod
    def from_json(cls, raw: str) -> Snapshot:
        return cls.from_dict(json.loads(raw))
