"""NetSentry — Data models for network state."""
from __future__ import annotations

import json
import time
from dataclasses import asdict, dataclass, field
from typing import Any, Dict, List, Optional

from shared import AlertLevel


# ── Process info (for tree view) ───────────────────────────────
@dataclass
class ProcessInfo:
    """Single process entry from /proc/[pid]/stat."""
    pid: int
    ppid: int
    name: str              # from /proc/[pid]/comm
    cmdline: str           # from /proc/[pid]/cmdline
    state: str             # single char: S, R, Z, T, etc.
    uid: int               # from /proc/[pid]/status
    has_network: bool = False  # True if process owns sockets
    children: List[int] = field(default_factory=list)

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> ProcessInfo:
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})


# ── Interface traffic stats ────────────────────────────────────
@dataclass
class InterfaceStats:
    """Per-interface network traffic counters from /proc/net/dev."""
    interface: str          # "wlan0", "eth0"
    rx_bytes: int           # cumulative received bytes
    tx_bytes: int           # cumulative transmitted bytes
    rx_packets: int
    tx_packets: int
    rx_errors: int
    tx_errors: int
    rx_drops: int
    tx_drops: int
    # Computed rates (bytes/sec, filled by daemon delta tracker)
    rx_rate: float = 0.0
    tx_rate: float = 0.0

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> InterfaceStats:
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})


# ── Socket entry ───────────────────────────────────────────────
@dataclass
class SocketEntry:
    """A single network socket from /proc/net/."""
    proto: str              # "tcp" | "udp"
    local_ip: str           # "0.0.0.0"
    local_port: int         # 22
    remote_ip: str          # "0.0.0.0" or peer
    remote_port: int        # 0 or peer port
    state: str              # "LISTEN" | "ESTABLISHED" | ...
    state_code: str         # "0A" raw hex
    uid: int
    inode: int
    pid: Optional[int] = None
    process_name: Optional[str] = None
    cmdline: Optional[str] = None
    remote_hostname: Optional[str] = None
    # GeoIP data (filled by backend.parsers.geoip)
    remote_country: Optional[str] = None
    remote_country_code: Optional[str] = None
    remote_city: Optional[str] = None
    remote_lat: Optional[float] = None
    remote_lon: Optional[float] = None
    remote_isp: Optional[str] = None
    remote_org: Optional[str] = None

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> SocketEntry:
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})


# ── Alert ──────────────────────────────────────────────────────
@dataclass
class Alert:
    """Security alert generated by the alert engine."""
    level: AlertLevel
    port: int
    proto: str
    process_name: Optional[str]
    pid: Optional[int]
    message: str
    timestamp: float = field(default_factory=time.time)

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> Alert:
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})


# ── Snapshot (full state at a point in time) ───────────────────
@dataclass
class Snapshot:
    """Complete network state snapshot written to JSON."""
    timestamp: float = field(default_factory=time.time)
    poll_interval_ms: int = 2000
    listening: List[SocketEntry] = field(default_factory=list)
    established: List[SocketEntry] = field(default_factory=list)
    alerts: List[Alert] = field(default_factory=list)
    summary: Dict[str, int] = field(default_factory=lambda: {
        "total_listening": 0,
        "total_established": 0,
        "alert_count": 0,
    })
    traffic: Dict[str, InterfaceStats] = field(default_factory=dict)
    processes: Dict[str, dict] = field(default_factory=dict)  # flat {pid_str: ProcessInfo_dict}
    geo_stats: Dict[str, Any] = field(default_factory=lambda: {
        "countries_count": 0,
        "unique_ips_per_country": {},
        "top_countries": [],
    })

    # ── Serialisation ──────────────────────────────────────────
    def to_dict(self) -> dict[str, Any]:
        return {
            "timestamp": self.timestamp,
            "poll_interval_ms": self.poll_interval_ms,
            "listening": [asdict(e) for e in self.listening],
            "established": [asdict(e) for e in self.established],
            "alerts": [asdict(a) for a in self.alerts],
            "summary": self.summary,
            "traffic": {name: asdict(stats) for name, stats in self.traffic.items()},
            "processes": self.processes,
            "geo_stats": self.geo_stats,
        }

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), ensure_ascii=False)

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> Snapshot:
        traffic_raw = d.get("traffic", {})
        traffic: Dict[str, InterfaceStats] = {}
        if isinstance(traffic_raw, dict):
            for name, stats in traffic_raw.items():
                if isinstance(stats, dict):
                    traffic[name] = InterfaceStats.from_dict(stats)

        return cls(
            timestamp=d.get("timestamp", time.time()),
            poll_interval_ms=d.get("poll_interval_ms", 2000),
            listening=[SocketEntry.from_dict(e) for e in d.get("listening", [])],
            established=[SocketEntry.from_dict(e) for e in d.get("established", [])],
            alerts=[Alert.from_dict(a) for a in d.get("alerts", [])],
            summary=d.get("summary", {}),
            traffic=traffic,
            processes=d.get("processes", {}) if isinstance(d.get("processes"), dict) else {},
            geo_stats=d.get("geo_stats", {}) if isinstance(d.get("geo_stats"), dict) else {},
        )

    @classmethod
    def from_json(cls, raw: str) -> Snapshot:
        return cls.from_dict(json.loads(raw))
